import React from 'react';
import {
  LayoutGrid,
  Grid,
  BookOpen,
  Timer,
  Activity,
  User,
  CheckCircle2,
  CheckCircle,
  AlertTriangle,
  AlertCircle,
  TrendingUp,
  TrendingDown,
  Sparkles,
  UploadCloud,
  FileText,
  RotateCcw,
  Play,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Sliders,
  ShieldAlert,
  Layers,
  Settings,
  Copy,
  FileCheck,
  Search,
  Filter,
  Eye,
  EyeOff,
  Flame,
  Clock,
  Compass,
  Award,
  BarChart3,
  HelpCircle,
  Hash,
  X,
  Check,
  Info,
  Zap,
  GraduationCap,
  ListTodo,
  RefreshCw,
  MoreHorizontal,
  Brain,
  Calculator,
  Frown,
  Dice5,
  Hourglass,
  History,
  Bookmark,
  Target,
  Lightbulb,
  PartyPopper,
  Shield,
  LogOut,
  Palette,
  ListCheck,
  Calendar,
  Smartphone,
  Monitor,
  Camera,
  Apple
} from 'lucide-react';

const ICON_MAP = {
  // Navigation
  'grid_view': LayoutGrid,
  'layout_grid': LayoutGrid,
  'map': LayoutGrid,
  'school': GraduationCap,
  'practice': Play,
  'play': Play,
  'quiz': Timer,
  'evaluate': Timer,
  'timer': Timer,
  'analytics': BarChart3,
  'insights': Activity,
  'activity': Activity,
  'trending_up': TrendingUp,
  'trending_down': TrendingDown,
  'trends': TrendingUp,
  'person': User,
  'profile': User,
  'checklist': ListTodo,
  'questions': BookOpen,
  'book_open': BookOpen,
  'history': History,

  // Status & Actions
  'check_circle': CheckCircle2,
  'check': Check,
  'task_alt': CheckCircle2,
  'warning': AlertTriangle,
  'alert_triangle': AlertTriangle,
  'error': AlertCircle,
  'alert_circle': AlertCircle,
  'info': Info,
  'help_center': HelpCircle,
  'help_circle': HelpCircle,
  'help': HelpCircle,
  'sparkles': Sparkles,
  'upload_file': UploadCloud,
  'upload_cloud': UploadCloud,
  'description': FileText,
  'file_text': FileText,
  'rotate_ccw': RotateCcw,
  'refresh': RefreshCw,
  'arrow_forward': ArrowRight,
  'arrow_right': ArrowRight,
  'arrow_back': ArrowLeft,
  'arrow_left': ArrowLeft,
  'chevron_right': ChevronRight,
  'chevron_down': ChevronDown,
  'chevron_left': ChevronLeft,
  'chevron_up': ChevronUp,
  'expand_more': ChevronDown,
  'settings': Settings,
  'sliders': Sliders,
  'copy': Copy,
  'search': Search,
  'filter': Filter,
  'eye': Eye,
  'eye_off': EyeOff,
  'visibility_off': EyeOff,
  'flame': Flame,
  'clock': Clock,
  'schedule': Clock,
  'emergency': AlertTriangle,
  'more_horizontal': MoreHorizontal,
  'zap': Zap,
  'award': Award,
  'celebration': PartyPopper,
  'party_popper': PartyPopper,
  'psychology': Brain,
  'brain': Brain,
  'calculate': Calculator,
  'calculator': Calculator,
  'sentiment_frustrated': Frown,
  'casino': Dice5,
  'timer_off': Hourglass,
  'bookmark': Bookmark,
  'precision': Target,
  'target': Target,
  'lightbulb': Lightbulb,
  'priority_high': AlertTriangle,
  'shield': Shield,
  'admin_panel_settings': Shield,
  'logout': LogOut,
  'palette': Palette,
  'list_check': ListCheck,
  'calendar': Calendar
};

export default function Icon({ name, size = 20, className = '', strokeWidth = 1.75, ...props }) {
  const normalized = (name || '').toLowerCase().replace(/-/g, '_').trim();
  const IconComponent = ICON_MAP[normalized] || HelpCircle;

  return (
    <IconComponent
      size={size}
      strokeWidth={strokeWidth}
      className={`inline-block flex-shrink-0 ${className}`}
      {...props}
    />
  );
}

export {
  LayoutGrid,
  BookOpen,
  Timer,
  Activity,
  User,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  TrendingUp,
  TrendingDown,
  Sparkles,
  UploadCloud,
  FileText,
  RotateCcw,
  Play,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Sliders,
  ShieldAlert,
  Layers,
  Settings,
  Copy,
  FileCheck,
  Search,
  Filter,
  Eye,
  EyeOff,
  Flame,
  Clock,
  Compass,
  Award,
  BarChart3,
  HelpCircle,
  Hash,
  X,
  Check,
  Info,
  Zap,
  GraduationCap,
  ListTodo,
  RefreshCw,
  MoreHorizontal,
  Brain,
  Calculator,
  Frown,
  Dice5,
  Hourglass,
  History,
  Bookmark,
  Target,
  Lightbulb,
  PartyPopper,
  Shield,
  LogOut,
  Palette,
  ListCheck,
  Grid,
  Calendar,
  Smartphone,
  Apple,
  Monitor,
  Camera
};
